/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;

import compiler.Bytecode.BytecodeCompiler;
import compiler.Lexer.Lexer;
import compiler.Lexer.SymbolKind;
import compiler.Parser.AST.MethodNode;
import compiler.Parser.AST.ProgramNode;
import compiler.Parser.Parser;
import compiler.Semantic.SemanticAnalyzer;

import java.io.IOException;
import java.io.StringReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.text.ParseException;

import static compiler.Parser.Parser.lookahead;
import static compiler.Parser.Parser.match;


public class Compiler {

    public static String[] argu;

    public static void main(String[] args) throws Exception {
        argu = args;
        Path filePath = Path.of(args[0]);
        String input = Files.readString(filePath);
        StringReader reader = new StringReader(input);
        Lexer lexer = new Lexer(reader);
        Parser parser = null;
        parser = new Parser(lexer);
        ProgramNode x = parser.getAST();
        new SemanticAnalyzer(x);
        BytecodeCompiler bc = new BytecodeCompiler(x);
        bc.getRender();

    }
}
