/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;

import compiler.Bytecode.BytecodeCompiler;
import compiler.Lexer.Lexer;
import compiler.Lexer.SymbolKind;
import compiler.Parser.AST.MethodNode;
import compiler.Parser.Parser;

import java.io.StringReader;
import java.text.ParseException;
import static compiler.Parser.Parser.lookahead;
import static compiler.Parser.Parser.match;


public class Compiler {
    public static void main(String[] args) throws ParseException {
        System.out.println("Hello from the compiler !");
        String input = "double _ysh1 >= 8.903 // test str =  ouioui \n var x int = 2; ";
        StringReader reader = new StringReader(input);
        Lexer lexer = new Lexer(reader);
        Parser parser = new Parser(lexer);
        BytecodeCompiler bc = new BytecodeCompiler(parser.getAST());

        try {
            new Parser(lexer);
        } catch (ParseException e) {
            throw new RuntimeException(e);
        }

    }
}
